language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dmitryv/docker-ci -f Dockerfile.dev .

script:
  #- docker run dmitryv/docker-ci npm run test -- --coverage
  - docker run -e CI=true dmitryv/docker-ci npm run test
